[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/tests"
script = "contracts/scripts"
broadcast = "contracts/broadcast"
cache_path = "contracts/cache"
libs = ["contracts/lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
